"""add profile evidence items"""
from alembic import op
import sqlalchemy as sa


revision = '178f73ddc6dc'
down_revision = '6b02_llm_metadata'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_evidence_items',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('education', 'certification', 'hackathon', 'event', 'community')"),
    sa.CheckConstraint("verification_status IN ('declared_only', 'linked', 'verified')"),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_evidence_items_candidate_id'), 'profile_evidence_items', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_evidence_items_candidate_id'), table_name='profile_evidence_items')
    op.drop_table('profile_evidence_items')
    # ### end Alembic commands ###
