"""add criterion families and frozen profile sources"""
from alembic import op
import sqlalchemy as sa


revision = '41c0cbaf4250'
down_revision = '178f73ddc6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_criteria', sa.Column('kind', sa.String(length=30), server_default='technical_skill', nullable=False))
    op.add_column('match_criteria', sa.Column('profile_evidence', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('need_criteria', sa.Column('kind', sa.String(length=30), server_default='technical_skill', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('need_criteria', 'kind')
    op.drop_column('match_criteria', 'profile_evidence')
    op.drop_column('match_criteria', 'kind')
    # ### end Alembic commands ###
