"""initial domain schema"""
from alembic import op
import sqlalchemy as sa


revision = '5aacc06c939c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_needs',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_role', sa.String(length=200), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.Column('analysis_version', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_results',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('need_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_type', sa.String(length=50), nullable=False),
    sa.Column('required_coverage', sa.Float(), nullable=False),
    sa.Column('preferred_coverage', sa.Float(), nullable=False),
    sa.Column('score_explanation', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.Column('analysis_version', sa.Text(), nullable=False),
    sa.Column('scoring_version', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('preferred_coverage >= 0 AND preferred_coverage <= 1'),
    sa.CheckConstraint('required_coverage >= 0 AND required_coverage <= 1'),
    sa.CheckConstraint('score >= 0 AND score <= 100'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['need_id'], ['organization_needs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_candidate_id'), 'match_results', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_match_results_need_id'), 'match_results', ['need_id'], unique=False)
    op.create_table('need_criteria',
    sa.Column('need_id', sa.Uuid(), nullable=False),
    sa.Column('skill_key', sa.String(length=64), nullable=False),
    sa.Column('skill_label', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority IN ('required', 'preferred')"),
    sa.ForeignKeyConstraint(['need_id'], ['organization_needs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('need_id', 'skill_key')
    )
    op.create_index(op.f('ix_need_criteria_need_id'), 'need_criteria', ['need_id'], unique=False)
    op.create_table('projects',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type = 'github'"),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'candidate_id')
    )
    op.create_index(op.f('ix_projects_candidate_id'), 'projects', ['candidate_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('need_id', sa.Uuid(), nullable=True),
    sa.Column('analysis_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('analysis_version', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(analysis_type = 'project' AND project_id IS NOT NULL AND need_id IS NULL) OR (analysis_type = 'need' AND need_id IS NOT NULL AND project_id IS NULL)"),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')"),
    sa.ForeignKeyConstraint(['need_id'], ['organization_needs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_need_id'), 'analysis_runs', ['need_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_project_id'), 'analysis_runs', ['project_id'], unique=False)
    op.create_table('match_criteria',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_id', sa.Uuid(), nullable=False),
    sa.Column('skill_key', sa.String(length=64), nullable=False),
    sa.Column('skill_label', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['need_criteria.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'criterion_id')
    )
    op.create_index(op.f('ix_match_criteria_match_id'), 'match_criteria', ['match_id'], unique=False)
    op.create_table('repository_snapshots',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('readme', sa.Text(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'project_id')
    )
    op.create_index(op.f('ix_repository_snapshots_project_id'), 'repository_snapshots', ['project_id'], unique=False)
    op.create_table('skill_evidence',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('skill_key', sa.String(length=64), nullable=False),
    sa.Column('skill_label', sa.String(length=200), nullable=False),
    sa.Column('evidence_status', sa.String(length=20), nullable=False),
    sa.Column('evidence_strength', sa.String(length=20), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("evidence_status IN ('observed', 'declared_only', 'not_found')"),
    sa.CheckConstraint("evidence_strength IN ('weak', 'medium', 'strong')"),
    sa.CheckConstraint("evidence_type IN ('project_description', 'readme', 'source_file', 'dependency_file', 'repository_language', 'user_claim')"),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'candidate_id'], ['projects.id', 'projects.candidate_id'], ),
    sa.ForeignKeyConstraint(['snapshot_id', 'project_id'], ['repository_snapshots.id', 'repository_snapshots.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_evidence_analysis_run_id'), 'skill_evidence', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_skill_evidence_candidate_id'), 'skill_evidence', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_skill_evidence_project_id'), 'skill_evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_skill_evidence_skill_key'), 'skill_evidence', ['skill_key'], unique=False)
    op.create_index(op.f('ix_skill_evidence_snapshot_id'), 'skill_evidence', ['snapshot_id'], unique=False)
    op.create_table('match_evidence',
    sa.Column('match_criterion_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['skill_evidence.id'], ),
    sa.ForeignKeyConstraint(['match_criterion_id'], ['match_criteria.id'], ),
    sa.PrimaryKeyConstraint('match_criterion_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_evidence')
    op.drop_index(op.f('ix_skill_evidence_snapshot_id'), table_name='skill_evidence')
    op.drop_index(op.f('ix_skill_evidence_skill_key'), table_name='skill_evidence')
    op.drop_index(op.f('ix_skill_evidence_project_id'), table_name='skill_evidence')
    op.drop_index(op.f('ix_skill_evidence_candidate_id'), table_name='skill_evidence')
    op.drop_index(op.f('ix_skill_evidence_analysis_run_id'), table_name='skill_evidence')
    op.drop_table('skill_evidence')
    op.drop_index(op.f('ix_repository_snapshots_project_id'), table_name='repository_snapshots')
    op.drop_table('repository_snapshots')
    op.drop_index(op.f('ix_match_criteria_match_id'), table_name='match_criteria')
    op.drop_table('match_criteria')
    op.drop_index(op.f('ix_analysis_runs_project_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_need_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_projects_candidate_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_need_criteria_need_id'), table_name='need_criteria')
    op.drop_table('need_criteria')
    op.drop_index(op.f('ix_match_results_need_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_candidate_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_table('organization_needs')
    op.drop_table('candidates')
    # ### end Alembic commands ###
