"""github_account_verification"""
from alembic import op
import sqlalchemy as sa


revision = 'a15_github_verification'
down_revision = 'a14_proof_requests'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_connections',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('github_user_id', sa.String(length=20), nullable=False),
    sa.Column('github_login', sa.String(length=100), nullable=False),
    sa.Column('access_ciphertext', sa.Text(), nullable=True),
    sa.Column('refresh_ciphertext', sa.Text(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'candidate_id')
    )
    op.create_index('uq_github_active_candidate', 'github_connections', ['candidate_id'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('uq_github_active_identity', 'github_connections', ['github_user_id'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('github_oauth_states',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_ciphertext', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_hash')
    )
    op.create_index(op.f('ix_github_oauth_states_candidate_id'), 'github_oauth_states', ['candidate_id'], unique=False)
    op.create_table('github_repository_links',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('github_repository_id', sa.String(length=20), nullable=False),
    sa.Column('installation_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('owner_id', sa.String(length=20), nullable=False),
    sa.Column('owner_login', sa.String(length=100), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('relationship', sa.String(length=30), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("owner_type IN ('User', 'Organization')", name='ck_github_owner_type'),
    sa.CheckConstraint("relationship IN ('personal_owner', 'account_access')", name='ck_github_relationship'),
    sa.ForeignKeyConstraint(['connection_id', 'candidate_id'], ['github_connections.id', 'github_connections.candidate_id'], ),
    sa.ForeignKeyConstraint(['project_id', 'candidate_id'], ['projects.id', 'projects.candidate_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_github_repository_links_connection_id'), 'github_repository_links', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    for table in ('github_connections', 'github_oauth_states', 'github_repository_links'):
        if op.get_bind().scalar(sa.text('SELECT count(*) FROM ' + table)):
            raise RuntimeError('GitHub provenance exists; preserve/export data before downgrade.')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_repository_links_connection_id'), table_name='github_repository_links')
    op.drop_table('github_repository_links')
    op.drop_index(op.f('ix_github_oauth_states_candidate_id'), table_name='github_oauth_states')
    op.drop_table('github_oauth_states')
    op.drop_index('uq_github_active_identity', table_name='github_connections', sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('uq_github_active_candidate', table_name='github_connections', sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('github_connections')
    # ### end Alembic commands ###
